CREATE TABLE `yue_chat_room` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '房间ID',
  `type` varchar(16) NOT NULL DEFAULT '' COMMENT 'radio/topic',
  `class` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '0-普通电台(听单) 1-私人FM',
  `creater_uid` int(10) unsigned NOT NULL DEFAULT '1001143' COMMENT '创建人ID',
  `text` varchar(255) NOT NULL DEFAULT '' COMMENT '用户电台房间分享文案',
  `group_id` varchar(32) NOT NULL DEFAULT '' COMMENT 'IM群ID',
  `listen_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '听单ID',
  `scene_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '场景ID',
  `channel_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '频道ID',
  `name` varchar(32) NOT NULL COMMENT '房间名称',
  `desc` varchar(256) NOT NULL COMMENT '房间描述',
  `desc_audio_url` varchar(128) NOT NULL COMMENT '房间描述音频',
  `desc_audio_time` tinyint(3) NOT NULL DEFAULT '0' COMMENT '房间描述语音时长秒',
  `icon` varchar(256) NOT NULL DEFAULT '' COMMENT '房间的icon',
  `img` varchar(128) NOT NULL COMMENT '封面图',
  `status` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '房间状态 0-下线 1-上线',
  `recommend` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '推荐 0/1',
  `score` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '推荐得分',
  `create_time` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '创建时间',
  `update_time` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '修改时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_status` (`status`) USING BTREE,
  KEY `idx_score` (`score`) USING BTREE,
  KEY `idx_creater_uid` (`creater_uid`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=212 DEFAULT CHARSET=utf8mb4 COMMENT='电台/话题房间'
